Repository jenkinsci/trilead-ssh2, pull requests merged in 2022-07, with the labels that each got.

#93 add support for hmac-sha2-512-etm@openssh.com hmac-sha2-256-etm@open…
  src/com/trilead/ssh2/crypto/cipher/CipherInputStream.java
  src/com/trilead/ssh2/crypto/cipher/CipherOutputStream.java
  src/com/trilead/ssh2/crypto/digest/MessageMac.java
  src/com/trilead/ssh2/transport/TransportConnection.java
  src/com/trilead/ssh2/transport/TransportManager.java
Labels: enhancement

#99 [JENKINS-69018] use constant MAX_PACKET_SIZE
  src/com/trilead/ssh2/transport/TransportConnection.java
Labels: bug

#104 Removal of unnecessary protobuf-java
  pom.xml
Labels: enhancement, dependencies
